apiVersion: workflows.dev/v1alpha1
kind: Workflow
metadata:
  namespace: pipelines
spec:
  events:
    - push

  branches:
    - "*"
    - "!master"

  defaults:
    image: 193814090748.dkr.ecr.us-east-1.amazonaws.com/nu-bookcase

  tasks:
    build-docs:
      resources:
        memory: 4Gi
        cpu: 2
      steps:
        - uses: checkout

        - name: build-docs
          workingDir: /nu-docs/
          run: |
            cp -r $(workspaces.projects.path)/data-platform-docs/. /nu-docs/docs
            npm run build
