site_name: Data Platform Documentation
site_description: Nubank's Data platform documentation
site_author: Squad Observability
site_url:
repo_url: https://github.com/nubank/data-platform-docs/
edit_uri: edit/master/
theme:
  name: 'material'
  analytics: {gtag: 'G-J9MKG0NSEP'}
  custom_dir: 'overrides'
  favicon: assets/nubank-favicon.ico
  logo: assets/nubank-logo.svg
  features:
    - tabs
  palette:
    primary: 'deep-purple'
    accent: 'deep-purple'

markdown_extensions:
  - admonition
  - sane_lists
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.mark
  - plantuml_markdown
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - toc:
      permalink: "#"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4/dist/mermaid.min.js
  - js/docs.js
  - js/search.js
  - js/elasticsearch.js
  - js/mark-as-outdated.js
  - js/gtm.js

plugins:
  - mkdocs-jupyter
  - git-revision-date-localized
  - minify
nav:
  - Home: "README.md"
  - What's new: "whats-new.md"
  - Glossary: "glossary.md"

  - About BU Squads:
    - About all squads: "about/data-bu-squads.md"
    - Data Infra overview: "about/data-infra/overview.md"
    - Analytics Productivity: "https://playbooks.nubank.com.br/squads/analytics-productivity/"
    - Onboarding:
      - Onboarding:
        - Dataset exercise: "onboarding/data-infra/dataset-exercise.md"
        - Introduction: "onboarding/data-infra/introduction.md"
        - Reading: "onboarding/data-infra/reading.md"
        - Setup: "onboarding/data-infra/setup.md"
        - Onboarding exercise: "onboarding/data-infra/service-exercise.md"
        - Data Infra history: "about/data-infra/history.md"
        - Data Infra anguages and stacks: "about/data-infra/services-language-stacks.md"
        - Slack channels: "about/data-infra/slack-channels.md"
        - Dashboards: "about/data-infra/dashboards-all.md"
  - Infrastructure:
    - Data Infra:
      - Bumping Spark: "infrastructure/data-infra/bumping-spark.md"
      - Run-time environment guide: "infrastructure/data-infra/guide-to-the-runtime-environment.md"
      - Inventory: "infrastructure/data-infra/inventory.md"
      - Multi-country: "infrastructure/data-infra/new-country.md"
      - Multi-country setup: "infrastructure/data-infra/multi_country_setup.md"
      - Query engines: "infrastructure/data-infra/query_engines.md"
      - Serving layer: "infrastructure/data-infra/serving_layer.md"
      - Testing models: "infrastructure/data-infra/testing-models.md"
      - Test custom images with ECR: "infrastructure/data-infra/test-images.md"
      - New shards: "infrastructure/data-infra/new_shards.md"
      - Granular access architecture: "infrastructure/granular-access-controls/architecture/README.md"
    - Data Access:
      - Setup a new country in Looker : "tools/looker/looker-country-setup.md"
      - Deploying Anduin in new country: "squad/data-access/deploying-multicountry-anduin.md"
    - Granular Access Controls:
      - Index: "infrastructure/granular-access-controls/index.md"
  - Data users:
    - FAQs:
      - All Dataplatform FAQs: "data-users/FAQs/README.md"
      - PII data deletion: "data-users/FAQs/pii-data.md"
      - Dataset series: "data-users/FAQs/dataset-series.md"
      - Error messages: "data-users/etl_users/FAQ.md"
    - Dataset series:
      - Dataset series on ETL: "data-users/etl_users/dss-on-etl.md"
      - Event DSS: "data-users/etl_users/dataset_series.md"
      - Archives: "data-users/etl_users/ingestion/archives.md"
      - Archive DSS: "data-users/etl_users/archived_datasets.md"
      - Manual DSS: "data-users/etl_users/manual_dataset_series.md"
      - Integrity exceptions: "data-users/etl_users/integrity_exceptions.md"
      - optimizing your SparkOp: "data-users/etl_users/optimizing_your_sparkop.md"
      - Schema validations: "data-users/etl_users/schema_validations.md"
      - Serving of datasets in staging environment: "data-users/etl_users/serving/serving_to_staging.md"
      - Custom S3 buckets on Databricks: "data-users/etl_users/custom-s3-buckets-on-databricks.md"

    - Streaming contracts:
      - Streaming contracts overview: data-users/streaming-contracts/streaming-contracts-intro.md
      - View batch and streaming contracts in BigQuery: data-users/streaming-contracts/views-bigquery.md
      - How fresh data is processed and transformed: data-users/streaming-contracts/data-freshness.md
    - Debugging load issues: squad/data-access/debugging-load-issues.md
    - Datasets:
      - Core Datasets: "datasets/core-datasets/README.md"

  - Process flows:
    - Overview of Data flow in ETL: "process-flows/overview-dataflow.md"
    - How the data from data sources is ingested into ETL environment and transformed: "process-flows/data-transformation.md"
    - Datomic data deletion: "process-flows/datomic-data-deletion-flow.md"
  - Oncall:
    - Data Infra:
      - Overview: "on-call/data-infra/README.md"
      - How to get help from other Squads: "on-call/data-infra/getting_help_from_other_squads.md"
      - Hausmeister: "on-call/data-infra/hausmeister.md"
      - Raw PII data access permission: "on-call/data-infra/raw-pii-access-permissions.md"
      - Incident response checklist: "on-call/data-infra/incident_response_checklist.md"
      - Monitoring nightly run: "on-call/data-infra/monitoring_nightly_run.md"
      - On-call runbook: "on-call/data-infra/on_call_runbook.md"
      - Operations How-tos: "on-call/data-infra/ops_how_to.md"
      - CLI examples: "on-call/data-infra/tools/cli_examples.md"
      - On-call engineer tools: "on-call/data-infra/tools/on-call-engineer-tool.md"
      - Dashboards: "on-call/data-infra/dashboards.md"
      - PII monitoring alert playbooks: "on-call/data-infra/pii_monitoring_alert_playbook.md"
      - Manual Dataset series alert playbook: "on-call/data-infra/mdss_alerts_playbook.md"
    - User support Documentation:
      - Dataset series: "on-call/data-infra/user-support.md"
    - Data access:
      - Rotations: "on-call/data-access/data-access-rotations.md"
      - Support: "on-call/data-access/data-support.md"
      - Itaipu PR reviewer: "on-call/data-access/itaipu-pr-reviewer.md"
      - On-call engineer: "on-call/data-access/on-call-engineer.md"
    - Data protection:
      - PII Expiry: "on-call/data-protection/pii_expiry.md"
  - Services:
    - Data layers: "services/data-ingestion/intro.md"
    - Data-ingestion:
      - Correnteza: "services/data-ingestion/correnteza.md"
      - Curva-de-rio: "services/data-ingestion/curva-de-rio.md"
      - Alph: "services/data-ingestion/alph.md"
    - Data processing:
      - Itaipu:
        - Overview: "services/data-processing/itaipu/itaipu.md"
        - Itaipu setup: "services/data-processing/itaipu/project_dev_setup.md"
        - Mergulho: "services/data-processing/itaipu/mergulho.md"
        - Dratini POC: "experiments/dratini.md"
        - Metadata POC: "experiments/metadata_testing.md"
        - Experiments: "home/experiment_description.md"
      - Metapod: "services/data-processing/metapod.md"
    - Data serving: "services/data-serving/serving-layer.md"
    - Data analysis and monitoring: "services/data-analysis-monitoring/analysis-monitoring.md"
  - How-tos:
    - Itaipu:
      - Itaipu setup: "services/data-processing/itaipu/project_dev_setup.md"
      - Creating basic dataset: "how-tos/itaipu/create_basic_dataset.md"
      - Contracts: "how-tos/itaipu/contracts.md"
      - Dataset series compaction: "how-tos/itaipu/dataset_series_compaction.md"
      - Datomic raw caches: "how-tos/itaipu/datomic-raw-cache.md"
      - Deploying new DAG: "how-tos/itaipu/deploying_new_dag.md"
      - Flow of Itaipu run: "how-tos/itaipu/flow_of_control.md"
      - Reviewing and merging a PR: "how-tos/itaipu/itaipu_reviewer.md"
      - Updating the log cache: "how-tos/itaipu/log_cache_update.md"
      - Opening PRs: "how-tos/itaipu/opening_prs.md"
      - Pororoca: "how-tos/itaipu/pororoca.md"
      - Retry logic in Itaipu: "how-tos/itaipu/retries.md"
      - Style guide: "how-tos/itaipu/styleguide.md"
      - Itaipu workflows: "how-tos/itaipu/workflow.md"
      - Performance: "how-tos/itaipu/performance/README.md"
      - Scala style guide: "style_guide.md"
      - Tekton: "how-tos/itaipu/tekton/README.md"
      - Tekton Deep-dive: "how-tos/itaipu/tekton/deep-dive.md"
      - Itaipu states: "services/data-processing/itaipu/itaipu_states.md"
      - Change continuous deployment pipeline: "how-tos/itaipu/change-continuous-deployment-pipeline.md"
      - Migrate SparkOps to Subproject: "how-tos/itaipu/migrate-sparkop-to-subproject.md"
      - Remove subproject: "how-tos/itaipu/remove-a-subproject.md"
    - Metapod: "how-tos/metapod.md"
    - Ryze:
      - Classification of data on S3: "how-tos/ryze/classify-s3.md"
      - Classify non pii databases: "how-tos/ryze/classify-non-pii-databases.md"
    - Data deletion:
      - Datomic data deletion: "how-tos/data-deletion/setup-datomic-pii-data-deletion.md"
      - PII and Personal data: "how-tos/data-deletion/pii_and_personal_data.md"
      - How to classify PII Datomic data on Ryze: "how-tos/data-deletion/pii-classification.md"
  - Tools:
    - Airflow: "tools/airflow.md"
    - Graphql: "tools/graphql_clients.md"
    - Databricks:
      - Overview: "tools/databricks/README.md"
      - API: "tools/databricks/api.md"
      - Libraries: "tools/databricks/libraries.md"
      - Setup NAT gateways for IP Filtering on Databricks: tools/databricks/ipfiltering.md
      - Bumping libraries: "tools/databricks/library_bump.md"
      - Databricks playbook: "tools/databricks/playbook.md"
      - S3 inventory: "tools/databricks/s3_inventory.md"
      - Single user clusters: "tools/databricks/single_user_clusters/README.md"
      - I AM roles in Databricks: "tools/databricks/single_user_clusters/meta-roles.md"
      - Single user clusters runbook: "tools/databricks/single_user_clusters/runbook.md"
      - Single user clusters automation workflow: "tools/databricks/single_user_clusters/automation_workflow.md"
      - Overloaded cluster: "tools/databricks/overloaded-cluster.md"
      - Ip access list: "tools/databricks/ip_access_list.md"
      - S3 cross account access: "tools/databricks/s3_cross_account_access.md"
      - PII access: "tools/databricks/pii_access_sync.md"
      - Secret tokens: "tools/databricks/secrets_tokens.md"
      - Automation decisions: "tools/databricks/single_user_clusters/automation_decisions.md"
      - Add bucket - Databricks: "tools/databricks/add_bucket.md" 
    - Frozen Suite:
      - Overview: "tools/frozen_suite/README.md"
      - User stories: "tools/frozen_suite/user_stories.md"
      - IceQL:
        - Overview: "tools/frozen_suite/iceql/README.md"
        - IceQL technical docs: "tools/frozen_suite/iceql/technical_docs.md"
        - IceQL step by step approach: "tools/frozen_suite/iceql/technical_docs.md"
      - Ice mold:
        - Overview: "tools/frozen_suite/ice_mold/README.md"
        - Ice mold technical docs: "tools/frozen_suite/ice_mold/technical_docs.md"
      - Iglu:
        - Overview: "tools/frozen_suite/iglu/README.md"
        - Iglu technical docs: "tools/frozen_suite/iglu/technical_docs.md"
        - Iglu Guide: "tools/frozen_suite/iceql/GUIDE.md"
    - Kimball: "tools/frozen_suite/iglu/kimball.md"
    - Looker:
      - Overview: "tools/looker/README.md"
      - Looker Common Tasks: "tools/looker/looker-common-tasks.md"
      - Looker Policies: "tools/looker/looker-policies.md"
      - Looker Support: "tools/looker/looker-support.md"
      - LookML Basics: "tools/looker/lookml-basics.md"
      - Looker New Country Setup: "tools/looker/looker-country-setup.md"
      - Looker Playbook: "tools/looker/playbook.md"
      - Looker known issues: "tools/looker/looker-known-issues.md"
  - Datasets:
    - Dataset creation flow: "datasets/basic-datasets/create-dataset-flow.md"
    - Create a dataset: "datasets/basic-datasets/create-dataset.md"
    - Write tests for dataset: "datasets/basic-datasets/testing-dataset.md"
    - Mandatory Verification checklist for a dataset: "datasets/basic-datasets/dataset-verification-checklist.md"
    - How to check dataset commit status on ETL: "datasets/basic-datasets/check-dataset-output.md"
    - Debug Dataset issues: "datasets/basic-datasets/debug-datasets.md"
    - Core Datasets: "datasets/core-datasets/README.md"
    - Contribution margin dataset: "squad/analytics-productivity/contribution_margin.md"
    - SparkOp best practices: "datasets/sparkop-bestpractices.md"
    - optimizing Skews: "data-users/etl_users/optimizing_skew.md"

  - Writing:
    - Writing runbooks: "writing/writing_runbooks.md"
    - Templates:
      - Alerts Playbook: "writing/templates/alerts-playbook.md"
      - Getting started: "writing/templates/getting-started.md"
      - Service Playbook: "writing/templates/service-playbook.md"
  - Datomic data deletion: "etl_operators/datomic_data_deletion.md" 
  