!unquoted procedure $addDataInfra($symbol)
  Boundary($symbol, "Data Infra")
!endprocedure

!unquoted procedure $addDataAccess($symbol)
  Boundary($symbol, "Data Access")
!endprocedure

!unquoted procedure $addDataProtection($symbol)
  Boundary($symbol, "Owner: Data Protection")
!endprocedure

!unquoted procedure $addEngHorizontals($symbol)
  Boundary($symbol, "Data Infra")
!endprocedure

!unquoted procedure $addInfoSec($symbol)
  Boundary($symbol, "Owner: InfoSec")
!endprocedure

!unquoted procedure $addITOps($symbol)
  Boundary($symbol, "Owner: IT Ops")
!endprocedure

!unquoted procedure $addIAMPolicies($symbol)
  System_Ext($symbol, "Nubank IAM", "IAM related containers such as nubank/iam-policies and AWS IAM itself")
!endprocedure

!unquoted procedure $addGovernanceOps($symbol)
  Person($symbol, "Analytics Engineering Chapter", "Wearing the 'Data Stewards' hat")
!endprocedure

!unquoted procedure $addDataConsumer($symbol)
  Person_Ext($symbol, "Nubanker", "Business Analyst, Data Scientist, Analytics Engineer, etc.")
!endprocedure

!unquoted procedure $addDecisionMakers($symbol)
  Person_Ext($symbol, "Decision Makers", "BU leadership, IT Risk, MT, etc.")
!endprocedure

!unquoted procedure $addMonitoring($symbol)
  System($symbol, "PII Exposure Monitoring", "Writes (user, ACG, platform, date) quadruples to dataset series and aggregates these data in BI dashboards.")
!endprocedure

!unquoted procedure $addItaipuRuntime($symbol)
  System($symbol, "Itaipu Runtime", "The nightly ETL run that writes data to S3.")
!endprocedure

!unquoted procedure $addOkta($symbol)
  System_Ext($symbol, "Okta", "Not considered for the initial tombinhos, but will be when we implement BigQuery.")
!endprocedure

!unquoted procedure $addDatabricks($symbol)
  System($symbol, "Databricks", "Including lambdas to manage auth{entication,orization}")
!endprocedure

!unquoted procedure $addGovMetadata($symbol)
  System($symbol, "access-control-metadata", "Itaipu subproject that contains ACGs.")
!endprocedure

!unquoted procedure $addIAM($symbol)
  System_Ext(iam, "AWS IAM")
!endprocedure

!unquoted procedure $addItaipuDatasets($symbol)
  System($symbol, "Itaipu Datasets", "Inside itaipu monorepo. Every dataset has ACG-related metadata such as clearance and restriction.")
!endprocedure

!unquoted procedure $addRequisitionSystem($symbol)
  System($symbol, "Requisition System", "Find (Google Data Studio dashboard) and request access (through Jiraya) to ACG(s) and interface for approvers (Jira).")
!endprocedure

!unquoted procedure $addSub1($itaipuDatasets, $govMeta, $dataConsumer)
  System_Ext(s3, "AWS S3")
  $addDataInfra(dataInfra) {
    $addItaipuRuntime(itaipuRuntime)
  }
  $addDataAccess(dataAccess) {
    $addDatabricks(databricks)
  }

  Rel(dataConsumer, databricks, "Run queries")
  Rel(databricks, s3, "Read data")
  Rel(itaipuRuntime, s3, "Write data")
  Rel(itaipuRuntime, $itaipuDatasets, "Get queries to run")
  Rel(itaipuDatasets, govMeta, "Link to ACG")
!endprocedure


!unquoted procedure $addSub2($piiMonitoring, $govMeta, $itaipuDatasets, $reqSystem, $dataProtection, $dataConsumer)
  $addGovernanceOps(govOps)
  $addDecisionMakers(decMakers)

  $addInfoSec(infoSec) {
      $addIAMPolicies(iam)
  }

  $addITOps(itOps) {
    System_Ext(maat, "Authorization System", "Primarily the 'scooby' service with auto approvals through access matrix, and manual approvals using the maat service.")
  }

  Rel(dataConsumer, reqSystem, "Request access")
  Rel(maat, govOps, "Ask for approve/deny if outside of access matrix")
  Rel(piiMonitoring, iam, "Extract ACGs per user for PII exposure OKR")
  Rel(govOps, govMeta, "Add/remove ACGs")

  Rel(piiMonitoring, itaipuDatasets, "Get enumerator for PII OKR by counting datasets per clearance/restriction")
  Rel(decMakers, piiMonitoring, "Monitor")
  Rel(reqSystem, iam, "Attach and revoke ACG policies to data account roles of the Nubanker in IAM")
  Rel(dataProtection, maat, "Maintain access matrix")
  BiRel(reqSystem, maat, "Jiraya => scooby (Kafka); scooby => Requisition System (AWS SQS)")
!endprocedure
