@startuml

!include includes/C4_Context.puml
!include includes/shared.puml

LAYOUT_WITH_LEGEND()
'LAYOUT_AS_SKETCH()

title System Context Diagram Granular Access Controls Project (C4 level: 1)

$addItaipuDatasets(itaipuDatasets)

$addDataConsumer(dataConsumer)

$addDataProtection(dataProtection) {
  $addRequisitionSystem(reqSystem)
  $addGovMetadata(govMeta)
  $addMonitoring(piiMonitoring)
}

$addSub1(itaipuDatasets, govMeta, dataConsumer)
$addSub2(piiMonitoring, govMeta, itaipuDatasets, reqSystem, dataProtection, dataConsumer)

@enduml
