@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate off

participant form as "Jira"
participant jira as "Jira\nAutomation"
participant okta2 as "Okta\nWorkflow"
participant matrix as "ACG Matrix\nLambda"
participant grant as "IAM Grant\nLambda(s)"
participant slack as "Slack"

[-> form: User submits form with datasets
[<- form: Thank you for submitting
form <- jira: Observe issue
activate jira

jira -> okta2: HTTP POST
activate okta2
destroy jira

loop For every ACG (because there can be multiple ACGs in the user request)
    alt Match found for chapter+squad in matrix: auto approval
      okta2 -> matrix: HTTP GET /...\n""{:user "nubanker@nubank.com.br""\n"" :acg  "RandomACG"}""
      activate matrix
      return: 204 No Content
      okta2 -> grant: HTTP POST /...\n""{:user "nubanker@nubank.com.br"""\n"" :acg  "RandomACG"}""
      activate grant
      return 201/202/204
      okta2 -> form: Comment on issue:\n"automatic approval granted for ACG X"
      note over okta2: Do we need a Slack notification or will closing\nthe Jira issue send a notification already?
      okta2 -> slack: Send notification: success, log out+in to use ACG
    else No match found: manual approval
      okta2 -> matrix: HTTP GET /...\n""{:user "nubanker@nubank.com.br""\n"" :acg  "RandomACG"}""
      activate matrix
      return: 404 Not Found
      okta2 -> form: Comment on original issue:\n"please await manual approval for ACG X"
      okta2 -> form: Create new issue for manual approval team
    end
end

alt If all subrequests are fulfilled
  form <- okta2: Close original issue
end

destroy okta2

@enduml
